name: Java CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Define OS matrix
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run Integration Test
        id: build
        run: ./gradlew integrationTest

      - name: List Files in Recordings Directory (Linux/macOS)
        if: ${{ runner.os != 'Windows' }} # Only run this step for Linux/macOS
        run: |
          echo "Listing files for Linux/macOS..."
          ls -lh build/gebContainer/recordings/*

      - name: Upload Recordings as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gebContainer-${{ matrix.os }}
          path: build/gebContainer/recordings/*/*.mp4