name: Java CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        # Uncomment the build-scan parameters if you want to publish a Gradle build scan
        # in order to see all the build logs, a complete task timeline, test outputs,
        # and the resolved dependencies of your build.
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Run Integration Test
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        id: build
        run: ./gradlew integrationTest
      - name: Upload Recordings as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gebContainer
          path: build/gebContainer/recordings/*/*.mp4

