name: Java CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Define OS matrix
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run Integration Test
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        id: build
        run: ./gradlew integrationTest

      - name: List Files in Recordings Directory
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]] || [[ "$RUNNER_OS" == "macOS" ]]; then
            ls -lh build/gebContainer/recordings/*
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            dir build\\gebContainer\\recordings\\*
          fi

      - name: Upload Recordings as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gebContainer-${{ matrix.os }}
          path: build/gebContainer/recordings/*/*.mp4